version: '3.7'

services:

  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=surveyjs
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
